<a href="https://colab.research.google.com/github/Maisha1714/Bootcamp_Exam/blob/main/Sentiment_classification_of_tweeter_comments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Sentiment Classification of Tweeter Comments**


In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("/content/reduced_100000_dataset.csv" , encoding='latin-1')
data

sentiment          id                          date     query  \
0              0  2200003196  Tue Jun 16 18:18:12 PDT 2009  NO_QUERY   
1              0  1467998485  Mon Apr 06 23:11:14 PDT 2009  NO_QUERY   
2              0  2300048954  Tue Jun 23 13:40:11 PDT 2009  NO_QUERY   
3              0  1993474027  Mon Jun 01 10:26:07 PDT 2009  NO_QUERY   
4              0  2256550904  Sat Jun 20 12:56:51 PDT 2009  NO_QUERY   
...          ...         ...                           ...       ...   
99995          0  1956786300  Thu May 28 22:41:13 PDT 2009  NO_QUERY   
99996          0  1997706652  Mon Jun 01 17:19:04 PDT 2009  NO_QUERY   
99997          4  1559579758  Sun Apr 19 11:30:43 PDT 2009  NO_QUERY   
99998          0  2264101639  Sun Jun 21 02:47:18 PDT 2009  NO_QUERY   
99999          0  2064141745  Sun Jun 07 05:21:44 PDT 2009  NO_QUERY   

                  user                                               text  
0      LaLaLindsey0609             @chrishasboobs AHHH I HOPE YOUR OK!!!   
1          sexygrneyes  @misstoriblack cool , i have no tweet apps  fo...  
2           sammydearr  @TiannaChaos i know  just family drama. its la...  
3          Lamb_Leanne  School email won't open  and I have geography ...  
4          yogicerdito                             upper airways problem   
...                ...                                                ...  
99995       BelleDessy  finallytryingto download evernote on my bberry...  
99996       DanaLouLou  @kimberly625 @amylovesoliver too late.    gues...  
99997            beex3             On the way to target with mah sistaaa   
99998         Sophs105  Hip is worse today, moving my leg causes pain....  
99999      samenriquez           1 more week? ( What to do? What to do??   

[100000 rows x 6 columns]

In [4]:
data.shape

(100000, 6)

#**What preprocessing steps are necessary before feeding the data into an ML model?**

In [5]:
value_count = data['sentiment'].value_counts()
value_count

sentiment
4    50057
0    49943
Name: count, dtype: int64

In [6]:
data['sentiment'] = data['sentiment'].replace(4,1)
data

sentiment          id                          date     query  \
0              0  2200003196  Tue Jun 16 18:18:12 PDT 2009  NO_QUERY   
1              0  1467998485  Mon Apr 06 23:11:14 PDT 2009  NO_QUERY   
2              0  2300048954  Tue Jun 23 13:40:11 PDT 2009  NO_QUERY   
3              0  1993474027  Mon Jun 01 10:26:07 PDT 2009  NO_QUERY   
4              0  2256550904  Sat Jun 20 12:56:51 PDT 2009  NO_QUERY   
...          ...         ...                           ...       ...   
99995          0  1956786300  Thu May 28 22:41:13 PDT 2009  NO_QUERY   
99996          0  1997706652  Mon Jun 01 17:19:04 PDT 2009  NO_QUERY   
99997          1  1559579758  Sun Apr 19 11:30:43 PDT 2009  NO_QUERY   
99998          0  2264101639  Sun Jun 21 02:47:18 PDT 2009  NO_QUERY   
99999          0  2064141745  Sun Jun 07 05:21:44 PDT 2009  NO_QUERY   

                  user                                               text  
0      LaLaLindsey0609             @chrishasboobs AHHH I HOPE YOUR OK!!!   
1          sexygrneyes  @misstoriblack cool , i have no tweet apps  fo...  
2           sammydearr  @TiannaChaos i know  just family drama. its la...  
3          Lamb_Leanne  School email won't open  and I have geography ...  
4          yogicerdito                             upper airways problem   
...                ...                                                ...  
99995       BelleDessy  finallytryingto download evernote on my bberry...  
99996       DanaLouLou  @kimberly625 @amylovesoliver too late.    gues...  
99997            beex3             On the way to target with mah sistaaa   
99998         Sophs105  Hip is worse today, moving my leg causes pain....  
99999      samenriquez           1 more week? ( What to do? What to do??   

[100000 rows x 6 columns]

In [7]:
data.isnull().sum()

sentiment    0
id           0
date         0
query        0
user         0
text         0
dtype: int64

In [8]:
data = data.drop('date', axis=1)
data

sentiment          id     query             user  \
0              0  2200003196  NO_QUERY  LaLaLindsey0609   
1              0  1467998485  NO_QUERY      sexygrneyes   
2              0  2300048954  NO_QUERY       sammydearr   
3              0  1993474027  NO_QUERY      Lamb_Leanne   
4              0  2256550904  NO_QUERY      yogicerdito   
...          ...         ...       ...              ...   
99995          0  1956786300  NO_QUERY       BelleDessy   
99996          0  1997706652  NO_QUERY       DanaLouLou   
99997          1  1559579758  NO_QUERY            beex3   
99998          0  2264101639  NO_QUERY         Sophs105   
99999          0  2064141745  NO_QUERY      samenriquez   

                                                    text  
0                 @chrishasboobs AHHH I HOPE YOUR OK!!!   
1      @misstoriblack cool , i have no tweet apps  fo...  
2      @TiannaChaos i know  just family drama. its la...  
3      School email won't open  and I have geography ...  
4                                 upper airways problem   
...                                                  ...  
99995  finallytryingto download evernote on my bberry...  
99996  @kimberly625 @amylovesoliver too late.    gues...  
99997             On the way to target with mah sistaaa   
99998  Hip is worse today, moving my leg causes pain....  
99999           1 more week? ( What to do? What to do??   

[100000 rows x 5 columns]

In [9]:
data = data.drop('query', axis=1)
data

sentiment          id             user  \
0              0  2200003196  LaLaLindsey0609   
1              0  1467998485      sexygrneyes   
2              0  2300048954       sammydearr   
3              0  1993474027      Lamb_Leanne   
4              0  2256550904      yogicerdito   
...          ...         ...              ...   
99995          0  1956786300       BelleDessy   
99996          0  1997706652       DanaLouLou   
99997          1  1559579758            beex3   
99998          0  2264101639         Sophs105   
99999          0  2064141745      samenriquez   

                                                    text  
0                 @chrishasboobs AHHH I HOPE YOUR OK!!!   
1      @misstoriblack cool , i have no tweet apps  fo...  
2      @TiannaChaos i know  just family drama. its la...  
3      School email won't open  and I have geography ...  
4                                 upper airways problem   
...                                                  ...  
99995  finallytryingto download evernote on my bberry...  
99996  @kimberly625 @amylovesoliver too late.    gues...  
99997             On the way to target with mah sistaaa   
99998  Hip is worse today, moving my leg causes pain....  
99999           1 more week? ( What to do? What to do??   

[100000 rows x 4 columns]

In [10]:
data.duplicated().sum()

0

**How would you convert tweets into numerical representations (TF-IDF,
CountVectorizer, Word2Vec)?**

In [11]:
x = data['text']
y = data['sentiment']
x

0                   @chrishasboobs AHHH I HOPE YOUR OK!!! 
1        @misstoriblack cool , i have no tweet apps  fo...
2        @TiannaChaos i know  just family drama. its la...
3        School email won't open  and I have geography ...
4                                   upper airways problem 
                               ...                        
99995    finallytryingto download evernote on my bberry...
99996    @kimberly625 @amylovesoliver too late.    gues...
99997               On the way to target with mah sistaaa 
99998    Hip is worse today, moving my leg causes pain....
99999             1 more week? ( What to do? What to do?? 
Name: text, Length: 100000, dtype: object

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(x)
print(vectorizer.get_feature_names_out())
print(X.toarray())

['00' '000' '0000' ... 'â¾ã' 'ãªâ' 'ãªâ²â']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


# **What sampling techniques (Oversampling, Undersampling, SMOTE) would you use to improve performance?**

As we have a very balanced dataset (imbalance less than 5%),we dont need over or undersampling or SMOTE because those are for class imbalance problem.

# **Which metrics (Accuracy, Precision, Recall, F1-score, AUC-ROC) should be used to evaluate a sentiment classifier, and why?**


Here we can use accuracy for balanced dataset,here we can use accuracy

# **You are training a Random Forest model for sentiment classification.**

In [14]:
from sklearn.metrics import accuracy_score,classification_report
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.4,random_state=42)

In [16]:
classifier = RandomForestClassifier()
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)
print(classification_report(y_test,y_pred,target_names = ['negative','positive']))

              precision    recall  f1-score   support

    negative       0.77      0.76      0.76     19930
    positive       0.76      0.77      0.77     20070

    accuracy                           0.77     40000
   macro avg       0.77      0.77      0.77     40000
weighted avg       0.77      0.77      0.77     40000



# **Which hyperparameters are crucial, and how would you optimize them using GridSearchCV or RandomizedSearchCV**

**We will use RandomizedSearchCV because it is used for large dataset**

In [20]:
from sklearn.model_selection import RandomizedSearchCV

param_dist = {
    'n_estimators': np.arange(50, 300, 50),  # Number of trees in the forest
    'max_depth': [None, 10, 20, 30, 40, 50],  # Maximum depth of each tree
    'min_samples_split': np.arange(2, 10, 2),  # Minimum samples required to split a node
    'min_samples_leaf': np.arange(1, 5, 1),  # Minimum samples required at a leaf node
    'criterion': ['gini', 'entropy']  # Function to measure the quality of a split
}

In [21]:
random_search = RandomizedSearchCV(
    estimator=classifier,  # The model to optimize
    param_distributions=param_dist,  # The hyperparameter grid
    n_iter=20,  # Number of random combinations to try
    cv=5,  # 5-fold cross-validation
    scoring='accuracy',  # Metric to evaluate model performance
    n_jobs=-1,  # Use all available CPU cores
    random_state=42  # Ensure reproducibility
)

In [23]:
random_search.fit(X_train, y_train)

print("Best Hyperparameters:", random_search.best_params_)

KeyboardInterrupt: 

# **How does each architecture handle CNN & LSTM sequential text data?**


In CNN,Convolution is used in feature extraction & it is used in image and text precessing and the pooling layer is used to reduce the dimentionality and keep the most relevant feature.If we work with short text and need speed we can work with CNN.the flatenning and dense layer of CNN helps us in classification.


In [2]:
!pip install tensorflow

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Conv1D, GlobalMaxPooling1D, LSTM, Dense, Dropout

In [8]:
embedding_layer = Embedding(input_dim=5000, output_dim=128, input_length=50)

# CNN Model
cnn_model = Sequential([
    embedding_layer,
    Conv1D(filters=128, kernel_size=5, activation='relu'),
    GlobalMaxPooling1D(),
    Dense(64, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

cnn_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

print("CNN Model Summary:")
cnn_model.summary()

CNN Model Summary:


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1d_3 (Conv1D)                    │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ global_max_pooling1d_3               │ ?                           │               0 │
│ (GlobalMaxPooling1D)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_4 (Dropout)                  │ ?                           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_9 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
embedding_layer = Embedding(input_dim=5000, output_dim=128, input_length=50)

lstm_model = Sequential([
    embedding_layer,
    LSTM(128, return_sequences=False),
    Dense(64, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

lstm_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

lstm_model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_5 (Dropout)                  │ ?                           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

# **Which one would you choose for short tweets vs long text reviews, and why?**


I will choose CNN for short tweets because it's fast and great with local patterns.

I will choose LSTM for long text review because it's understands context, handles longer sequences

#**How does BERT handle contextual word meanings compared to Word2Vec or TF-IDF?**

BERT, Word2Vec, and TF-IDF handle contextual word meanings differently. BERT provides dynamic embeddings, adapting word meanings based on context with a bidirectional approach, making it ideal for complex sentences and polysemy.Word2Vec offers static embeddings, giving each word a fixed vector regardless of context, which is suitable for semantic similarity but lacks contextual sensitivity.TF-IDF uses a frequency-based approach, focusing on word importance in documents without considering context or word order, making it useful for simple keyword extraction but not for deep understanding.

# **What modifications (fine-tuning, freezing layers) would improve sentiment classification performance?What are the key steps for fine-tuning an LLM on a sentiment dataset?**

fine tuning,freezing layers,Data Augementation,Hyperparameter Optimization.

# **key steps**

Step 1: Choose a pre-trained model and a dataset

Step 2: Load the data to use

Step 3: Tokenizer

Step 4: Initialize the base model

Step 5: Evaluate method

Step 6: Fine-tune using the Trainer Method